name: Deploy to Producion
on:
  push:
    branches: ["production"]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    steps:
      - name: deploy crude way
        run: |
          mkdir .ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> .ssh/secret_key
          chmod 400 .ssh/secret_key
          ssh -o StrictHostKeyChecking=no -i .ssh/secret_key ubuntu@${{secrets.SSH_HOST_PROD}} -t "cd monorepo && git checkout production && git pull origin production && export PATH=/home/ubuntu/.nvm/versions/node/v22.17.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && pnpm install && pnpm build && pm2 restart "api" && pm2 restart "web" && pm2 restart "ws""
