name: Deploy to Staging
on:
  push:
    branches:
      - "master"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    steps:
      - name: add SSH private Key
        run: |
          cd ~
          rm -rf .ssh
          mkdir .ssh
          cd .ssh
          ls -a
          echo "key: ${{env.SSH_PRIVATE_KEY}}" > secret_key
          cat ~/.ssh/secret_key
