name: Deploy to Staging
on:
  push:
    branches:
      - "master"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    steps:
      - name: add SSH private Key
        run: |
          mkdir .ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> .ssh/secret_key
          ls .ssh
