name: Deploy to Staging
on:
  push:
    branches:
      - "master"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    steps:
      - name: add SSH private Key
        run: |
          mkdir .ssh
          echo "key: ${{env.SSH_PRIVATE_KEY}}" &> .ssh/secret_key
          cat ~/.ssh/secret_key
          ls -a
