name: Deploy to Staging
on:
  push:
    branches:
      - "master"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    steps:
      - name: add SSH private Key
        run: |
          mkdir .ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> .ssh/secret_key
          cat ~/.ssh/secret_key
          echo "${{secrets.SSH_HOST}}" &> .ssh/known_hosts
          ssh -i .ssh/secret_key ubuntu@${{secrets.SSH_HOST}}
          ls -lrt
