name: Deploy to Staging
on:
  push:
    branches:
      - "master"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    steps:
      - name: add SSH private Key
        run: |
          rm -rf .ssh
          mkdir .ssh
          ls -a
