name: Deploy to Staging
on:
  push:
    branches:
      - "master"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    steps:
      - name: add SSH private Key
        run: |
          rm -rf .ssh
          mkdir .ssh
          cd .ssh
          touch secret_key
          echo "key: ${{env.SSH_PRIVATE_KEY}}" &> secret_key
          cd ~
          cat ~/.ssh/secret_key
